### ISSUE TITLE
Two GenerationModel classes

### ISSUE THREAD

**Issue by johpiip** [HSLdevcom/helmet-model-system#126]
There are two classes called `GenerationModel`:

https://github.com/HSLdevcom/helmet-model-system/blob/2e8de090877a7af0fe1055d6e2997496a318c8e7/Scripts/models/generation.py#L7

https://github.com/HSLdevcom/helmet-model-system/blob/f049811b41a827239acee4e8369027beaff6a4eb/Scripts/models/logit.py#L390

Super confusing!

**Comment by zptro** [comment]
Any ideas on how to name them, @johpiip ? :)

**Comment by johpiip** [comment]
The logit model one could probably be `TourCombinationModel` as it chooses between different tour combinations whereas the `GenerationModel` in `generation.py` just defines how many tours people make (of different purposes). Yes, I can change this myself but I added it here as a reminder. 😄
