### ISSUE TITLE
Dividing integers

### ISSUE THREAD

**Issue by TimoElolahde** [HSLdevcom/helmet-model-system#133]
In some cases there is a possibility of dividing integers, which may cause problems e.g. on following lines

https://github.com/HSLdevcom/helmet-model-system/blob/313283a5a5d6c2edbfd97bc272ef2d521e00f368/Scripts/modelsystem.py#L169

https://github.com/HSLdevcom/helmet-model-system/blob/313283a5a5d6c2edbfd97bc272ef2d521e00f368/Scripts/assignment/emme_assignment.py#L205

**Comment by TimoElolahde** [comment]
Also line 178
        dtt = travel_time + wt_weight*((5/3*fwt)**0.8 - fwt)
and the end of line 730
        segment["@wait_time_dev"] = headway_sd**2 / (2*line.headway)
in emme_assignment.py may cause problems.

I have already corrected these four formulas in my own files but they are not in GitHub yet.

**Comment by TimoElolahde** [comment]
Here are links to the lines mentioned in my previous comment

https://github.com/HSLdevcom/helmet-model-system/blob/313283a5a5d6c2edbfd97bc272ef2d521e00f368/Scripts/assignment/emme_assignment.py#L166

https://github.com/HSLdevcom/helmet-model-system/blob/313283a5a5d6c2edbfd97bc272ef2d521e00f368/Scripts/assignment/emme_assignment.py#L730

**Comment by TimoElolahde** [comment]
I have already corrected four previous formulas in my own files but they are not in GitHub yet.

**Comment by zptro** [comment]
#137
