### ISSUE TITLE
Flaky test "tests\integration\test_models.py::ModelTest::test_agent_model"

### ISSUE THREAD

**Issue by Mew-www** [HSLdevcom/helmet-model-system#140]
Would need information from @zptro to figure how it is intended to be.

Part what fails every few runs:
![image](https://user-images.githubusercontent.com/23376146/75877670-e3adbd00-5e20-11ea-9f53-e4f50aca4472.png)

else succeeding (with no changes, just a re-run):
![image](https://user-images.githubusercontent.com/23376146/75877749-0c35b700-5e21-11ea-9566-aeb0a9783cd1.png)

Specific part what breaks:
![image](https://user-images.githubusercontent.com/23376146/75877844-3dae8280-5e21-11ea-9b7a-3f8c83b070e2.png)

**Comment by johpiip** [comment]
This? https://github.com/HSLdevcom/helmet-model-system/issues/129

**Comment by zptro** [comment]
Fixed in f49e3e76e87509a8e3ca1ddc5752a04479c0de78
