### ISSUE TITLE
assignment_test.py not running on Linux

### ISSUE THREAD

**Issue by johpiip** [HSLdevcom/helmet-model-system#18]
![assignment_test_issue](https://user-images.githubusercontent.com/20718745/57611955-994f0d00-757c-11e9-898c-6492b4a89429.png)

Here is the console log. Sorry for the screenshot, copying text from XTerm proved to be too difficult... :smile: My Emme version is 4.3.5 and its Python version is 2.7.11.

**Comment by johpiip** [comment]
@zptro ^

**Comment by paasovaara** [comment]
Seems like a bug in EMME?

**Comment by johpiip** [comment]
Solved! We forgot to run `batin_tyhjapyoraverkko.mac` when creating the bicycle scenario. No changes needed!
