### ISSUE TITLE
Extra attributes needed before initialized

### ISSUE THREAD

**Issue by zptro** [HSLdevcom/helmet-model-system#200]
This macro uses extra attribute `@lvari`: 
https://github.com/HSLdevcom/helmet-model-system/blob/637e21c7341fb44603f55ccfa815497c8daca4bf/Database/4verkkoa_HM40.mac#L155

But extra attributes are not initialized until here:
https://github.com/HSLdevcom/helmet-model-system/blob/637e21c7341fb44603f55ccfa815497c8daca4bf/Database/4verkkoa_HM40.mac#L160

**Comment by TimoElolahde** [comment]
Originally macro extra_attr.mac has been used when a new Emme project is created. The macro defines extra attributes needed in scenarios 19 and 21-23. When the definitions are made once the macro is no more needed but new network files replacing old ones can be read e.g. with macro batin_4verkkkoa_M2019.mac.

The macro muuta_linkkien_attribuutit_eikorj.mac has been used as a part of the construction process of the network file d211_verkko*.in. When the network file is released this macro is no more needed.

Now Atte has replaced the batin_4verkkkoa_M2019.mac with a new macro 4verkkkoa_HM40.mac and included also these macros in the process. It might be wise to run (in addition the so called f-macros) also the macro muuta_linkkien_attribuutit_eikorj.mac but I’m not sure whether running macro extra_attr.mac is necessary.

**Comment by zptro** [comment]
@TimoElolahde Could you fix this quickly, just flipping them around so that `extra_attr.mac` comes before `muuta_linkkien_attribuutit_eikorj.mac`?

**Comment by TimoElolahde** [comment]
A new version of the macro is in https://github.com/HSLdevcom/helmet-model-system/blob/TimoElolahde-patch-1/Database/4verkkoa_HM40.mac
Calling macro extra_attr.mac is not moved but changed to a comment.
