### ISSUE TITLE
Helmet 4.exe crashes if Helmet-path doesn't exist

### ISSUE THREAD

**Issue by samulikyytsonen** [HSLdevcom/helmet-model-system#227]
Helmet user interface crashes if previously defined "HELMET-skenaarioiden tallennuspolku" path doesn't exist anymore (e.g. folder deleted). As consequence, user interface shows empty screen without warning. Not sure if the problem occurs with other defined folders.

**Comment by zptro** [comment]
Duplicate of https://github.com/HSLdevcom/helmet-ui/issues/19
