### ISSUE TITLE
Matrice sizes and zone numbers are not checked for consistency with zone data and network

### ISSUE THREAD

**Issue by zptro** [HSLdevcom/helmet-model-system#228]
Indata validation should included matrices.

**Comment by zptro** [comment]
A possible additional feature would be to add zero rows and columns to base matrices automatically if zones have been added to zone data and network. Project-wise fine-grained zone divisions do not necesserily require freight traffic to be as fine-grained. And the start matrices going to first assignment iteration will need to be from a previous model run anyway. 

A warning should then be printed as well.

**Comment by samulikyytsonen** [comment]
Sounds good! Densifying zones is needed almost in every project and so far it's done with division numbers and multiple project banks. This would reduce amount of work significantly.

I think this solution should work fine, although I'm not sure how and where base matrices are excactly used.
