### ISSUE TITLE
Calculate 24h results with cba.py 

### ISSUE THREAD

**Issue by atte-wsp** [HSLdevcom/helmet-model-system#234]
Are peak hour (aht, pt, iht) results needed in Excel Workbook, as a background information or other reasons, or could we expand them to 24 hours in `cba.py` with `param.volume_factors`. Writing to file and printing would be a bit easier when aggregated to single time period.

**Comment by zptro** [comment]
The original reason is that it is important to separate the effects for new travellers from effects for old travellers. Right now summing to the whole day is done after that step. But summing to the whole day could indeed be done separately for old and new travellers in the script.

**Comment by zptro** [comment]
One point in doing the calculations in excel is that it makes it easier to understand for users who are not comfortable with programming. The calculations also stay documented better if the excel is stored separately from the scripts.

**Comment by atte-wsp** [comment]
Yep, I was thinking the same. Some times it is useful also to investigate gains and revenues by time period. 

But for us getting spatial distribution of gains was more important and I couldn't find reasonable way to keep time periods and write those to file. Also some parts of CBA (miles and transit miles) were already using 24h values, so it was consistent to use the same time aggregation for all.

However these might be user dependent issues, so we could keep modified `cba.py ` only for our internal use.

**Comment by atte-wsp** [comment]
This can be closed. If needed the #241 contains 24h results to ease visualizing results on map.
