### ISSUE TITLE
Matrix check crashes with fixed transit costs

### ISSUE THREAD

**Issue by atte-wsp** [HSLdevcom/helmet-model-system#239]
Base demand assignment (fixed cost = true) is crashing due to the matrix check is trying to find `bike_work` from cost OMX-file. Opening omx-files as MatrixData-object checks that all param.transport_classes are found and this crashes when base demand assignment is trying to read read fixed transit costs from file. 

If I'm correct the cost_ttt .omx should not include bike_work?

> IndexError: File C:\Users\YY\helmet\system-results\V2016\Matrices\cost_aht.omx does not contain bike_work matrix.

**Comment by zptro** [comment]
I think an ok solution for now is to not validate the cost matrix. If the file contains wrong data, the model run will crash almost immediately.

If the transit cost matrix has too few rows or columns, zeros should **not** be added.
