### ISSUE TITLE
Save total travel time matrix

### ISSUE THREAD

**Issue by samulikyytsonen** [HSLdevcom/helmet-model-system#248]
Not an issue, but a wish, that total travel time (actual time) matrix is saved while trip_part matrices are saved. Would be nice if saved in omx-matrices since the matrice often used in evaluations.

**Comment by zptro** [comment]
Calculation of this matrix would be easy to add to the official code. 

Not sure if I would add saving to omx to the official code though. But that would be really easy for the user to add as a script if wanted.
