### ISSUE TITLE
summary results

### ISSUE THREAD

**Issue by TimoElolahde** [HSLdevcom/helmet-model-system#38]
Perhaps this file could also be in repository UI.

Atte Supponen suggested in his e-mail in Wed 19.6.2019 9:52 that summary results e.g. comparison of modal split in some areas could be useful in checking the validity of model run. These results could be presented as business graphic in addition to number tables.

**Comment by zptro** [comment]
Summary of for instance modal splits

**Comment by zptro** [comment]
Also MAL indicators (one value per indicator), perhaps in cba excel.

**Comment by zptro** [comment]
Wish list from HSL transit planners:
- sums of car and transit trips per time period
- sums of travel times per time period for whole model area
