### ISSUE TITLE
Toll cost is written to result matrices for trucks

### ISSUE THREAD

**Issue by zptro** [HSLdevcom/helmet-model-system#462]
Truck and trailer truck assignment is not affected by toll cost. However, in this line we still calculate toll cost as if they would be affected. This later on affects the travel time matrix calculation, as that is calculated by subtracting the cost matrix from the generalized cost matrix.

https://github.com/HSLdevcom/helmet-model-system/blob/4939e0505b8bde26f53116c89c31ff747cf74c45/Scripts/assignment/datatypes/car.py#L27

**Comment by zptro** [comment]
This was changed to include trucks and trailer trucks in Helmet 4.1. Previously the travel time matrices for these assignment classes were empty.

https://github.com/HSLdevcom/helmet-model-system/blob/4939e0505b8bde26f53116c89c31ff747cf74c45/Scripts/assignment/assignment_period.py#L432-L433

**Comment by zptro** [comment]
This is were we set the actual link cost for trucks. Unfortunately this involves a hard-coded setting of `value_of_time_inv` parameter so that it translates length (in km) to time equivalents (in min).

https://github.com/HSLdevcom/helmet-model-system/blob/4939e0505b8bde26f53116c89c31ff747cf74c45/Scripts/assignment/datatypes/car_specification.py#L40-L42

**Comment by zptro** [comment]
@johpiip

**Comment by johpiip** [comment]
Thank you @zptro for verifying that truck and trailer truck assignment should not be affected by toll costs. I was wondering the same lines yesterday and your explanation is very helpful. I will continue from here!
