### ISSUE TITLE
Congested transit assignment not converging in `olusanya`

### ISSUE THREAD

**Issue by johpiip** [HSLdevcom/helmet-model-system#473]
Either https://github.com/HSLdevcom/helmet-model-system/commit/ac46d6e3719dca1105b9f844805a72c53a57f214 or https://github.com/HSLdevcom/helmet-model-system/commit/1b1bd9dcd9a79aa2c9027409f2988212a5f3e9ad in `olusanya` has likely caused an issue where congested transit assignment does not converge even if it has converged previously.

**Comment by zptro** [comment]
Are there any other strange results, @johpiip? The described issue suggests that we get too many transit trips, can that be observed for instance in mode split?

**Comment by johpiip** [comment]
@zptro Looking at result_summary.txt for 2018, assigned demand and mode shares have not changed (0,03 % changes at most) but vehicle kilometers are weird. car_leisure is +7 %, transit leisure +19 %, trailer truck - 10 %, aux_transit +26 %, others at most +- 2 %.

**Comment by johpiip** [comment]
When I ran road toll analyses, everything converged. Either there is something going on in https://github.com/HSLdevcom/helmet-model-system/commit/ac46d6e3719dca1105b9f844805a72c53a57f214 or then it is something else entirely.

**Comment by johpiip** [comment]
Should I merge https://github.com/HSLdevcom/helmet-model-system/pull/469 and check again?
