### ISSUE TITLE
requests.txt is missing modules?

### ISSUE THREAD

**Issue by hsl-petrhaj** [HSLdevcom/helmet-model-system#492]
requests.txt should include at least pandas and numpy

**Comment by zptro** [comment]
I guess you mean `requirements.txt`. That file only lists what is needed on top of the packages already included in the Emme Python distribution. Pipfile lists the packages needed if running the code standalone.

**Comment by hsl-petrhaj** [comment]
I most likely forgot some step then. I think my VS Code did not take the env file into account. Anyway, will get back to this next week.
