### ISSUE TITLE
Emme-Desktop tools in a separate folder

### ISSUE THREAD

**Issue by hsl-petrhaj** [HSLdevcom/helmet-model-system#507]
Should we move Emme-Desktop tools into a separate folder? Now it feels like network_link_printing.py and network_validation.py are kinda randomly in the root folder.
@johpiip  @zptro

**Comment by johpiip** [comment]
A great idea! You can add a folder `Scripts/tools` for example, and move scripts there and test that they still work.

**Comment by hsl-petrhaj** [comment]
already fixed.
