### ISSUE TITLE
Roll out type hints

### ISSUE THREAD

**Issue by zptro** [HSLdevcom/helmet-model-system#510]
Type hints were introduced in python 3.5, so we should consider using them on a large scale.

**Comment by hsl-petrhaj** [comment]
Good old Python becoming more and more like Java :-)
But jokes aside, when I was trying to understand some parts of the code, missing types made it even harder. And I can guess the IDE could also get smarter based on these?

**Comment by hsl-petrhaj** [comment]
@zptro Is there any way in VS code to speed up the work on types? Some add-on to infer the types and ask when not obvious?

**Comment by hsl-petrhaj** [comment]
Most important: functions (args and return values).
