### ISSUE TITLE
Deterministic runs for agent-based model

### ISSUE THREAD

**Issue by hsl-petrhaj** [HSLdevcom/helmet-model-system#515]
Don't know if this is even possible. But maybe we should at least _determine_ how many runs are needed to get stable results that can be used officially.

**Comment by johpiip** [comment]
Our agent model synthetizator relies on `random` so it will always be stochastic. The random seed is set here:
https://github.com/HSLdevcom/helmet-model-system/blob/9ca9d716693e8af469b5730fc6199cb83cb7eb51/Scripts/parameters/zone.py#L4-L7

A quick plan would  be to:
1. Make a few agent model runs (for example, on test network) to verify that all stochasticity is indeed controlled by `population_draw`.
2. Once that is verified, make several agent model runs on a real network (for example, 2018) and compare results: agents, tours, stuff on `result_summary.txt` etc.

However, I am closing this as this is not really a model development issue! You should copy this to Trello on "Ideat" as this is a great idea in model usage context!

**Comment by hsl-petrhaj** [comment]
done
